### ISSUE TITLE
Playground examples don't work

### ISSUE THREAD

**Issue by matteomalosio** [lukasmasuch/streamlit-pydantic#58]
Dear developers,
I just want to communicate that the playground don't work.
Best,
Matteo

**Comment by lukasmasuch** [comment]
Fixed :) the playground is working again: https://st-pydantic.streamlit.app/

**Comment by matteomalosio** [comment]
Thank you!
But... I'm sorry... if I select Data Validation it still doesn't work.
Thank you very much for your work!
Best,
Matteo

Il giorno dom 18 ago 2024 alle ore 16:48 Lukas Masuch <
***@***.***> ha scritto:

**Comment by lukasmasuch** [comment]
Thanks for checking. I will fix it today :)

**Comment by lukasmasuch** [comment]
Fixed it 👍
